### ISSUE TITLE
HWQ2

### ISSUE THREAD

**Issue by Aureni** [chulminy/AE121#11]
for part b) I dont understand what it is required since have tried various usage of randperm as demonstrated below but all of them keep getting denied.

vector2=vector1 ;
vector2 = randperm (30);

vector2 = vector1(randperm(length(vector1)));

vector2(:,:) = randperm(30);

vector2 = shuffle (vector1);

vector2 = vector1(randperm(30));

**Comment by jpconnel** [comment]
It is asking for the same elements as in part a) to be returned in a shuffled form using the randperm function. Check out the MATLAB doc for randperm and the different inputs you can use.

https://www.mathworks.com/help/matlab/ref/randperm.html

**Comment by chulminy** [comment]
There is an issue for generating random numbers. The random number generated from the model solution and yours are different. Your implementation is correct. 

Check the modified problem. 'vector2' is given now.
